site_name: Toggl API Wrapper
site_url: https://ddkasa.github.io/toggl-api-wrapper/
use_directory_urls: false
site_description: Simple Toggl API wrapper for non-premium features.
site_author: David Kasakaits
docs_dir: "docs/"

repo_name: ddkasa/toggl-api-wrapper
repo_url: https://www.github.com/ddkasa/toggl-api-wrapper

edit_uri: blob/master/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Getting Started:
      - Overview: README.md
      - Installation: user-guide/installation.md
      - Examples: user-guide/examples.md
  - API Reference:
      - Overview: api-guide/index.md
      - Configuration: api-guide/config.md
      - Endpoint: api-guide/endpoint.md
      - User: api-guide/user.md
      - Cache: api-guide/cache.md
      - Models: api-guide/model.md
      - Organization: api-guide/organization.md
      - Workspace: api-guide/workspace.md
      - Trackers: api-guide/tracker.md
      - Projects: api-guide/project.md
      - Client: api-guide/client.md
      - Tags: api-guide/tag.md
      - Reports: api-guide/reports.md
  - Changelog: CHANGELOG.md
  - About:
      - Contributing: CONTRIBUTING.md
      - License: LICENSE.md

extra_css:
  - stylesheet/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click
  - md_in_html
  - admonition

copyright: Copyright &copy; 2024 David Kasakaitis

# hooks:
# - docs/hooks.py

plugins:
  - search
  - autorefs
  - glightbox
  - macros
  - mermaid2
  - literate-nav:
      nav_file: docs/README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - callouts
  - panzoom:
      full_screen: true
watch:
  - toggl_api
