site_name: Toggl API Wrapper
site_url: ""
use_directory_urls: false
site_description: Simple Toggl API wrapper for non-premium features.
site_author: David Kasakaits
docs_dir: 'docs/'


repo_name: ddkasa/toggl-api-wrapper
repo_url: https://www.github.com/ddkasa/toggl-api-wrapper


edit_uri: blob/master/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: README.md
  - Getting Started: getting-started.md
  - API Reference: user-guide/
  - Development: dev-guide/
  - Release Notes: about/release-notes.md
  - About:
    - Contributing: about/CONTRIBUTING.md
    - License: about/LICENSE.md

extra_css:
  - stylesheet/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click

copyright: Copyright &copy; 2024 David Kasakaitis

# hooks:
  # - docs/hooks.py

plugins:
  - search
  - autorefs
  - literate-nav:
      nav_file: docs/README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true

watch:
  - toggl_api
