classDiagram
  class toggl_api {
  }
  class _client {
  }
  class _exceptions {
  }
  class _organization {
  }
  class _project {
  }
  class _tag {
  }
  class _tracker {
  }
  class _user {
  }
  class _utility {
  }
  class _version {
  }
  class config {
  }
  class meta {
  }
  class _base_endpoint {
  }
  class _body {
  }
  class _cached_endpoint {
  }
  class _enums {
  }
  class cache {
  }
  class _base_cache {
  }
  class _json_cache {
  }
  class _sqlite_cache {
  }
  class models {
  }
  class _decorators {
  }
  class _models {
  }
  class _schema {
  }
  class reports {
  }
  class workspace {
  }
  toggl_api --> _client
  toggl_api --> _exceptions
  toggl_api --> _organization
  toggl_api --> _project
  toggl_api --> _tag
  toggl_api --> _tracker
  toggl_api --> _user
  toggl_api --> _version
  toggl_api --> _base_cache
  toggl_api --> models
  toggl_api --> workspace
  _client --> _exceptions
  _client --> meta
  _client --> cache
  _client --> models
  _organization --> meta
  _organization --> meta
  _organization --> cache
  _organization --> models
  _project --> _exceptions
  _project --> _utility
  _project --> meta
  _project --> cache
  _project --> models
  _tag --> _exceptions
  _tag --> meta
  _tag --> cache
  _tag --> models
  _tracker --> _exceptions
  _tracker --> _utility
  _tracker --> meta
  _tracker --> cache
  _tracker --> models
  _user --> meta
  meta --> _base_endpoint
  meta --> _body
  meta --> _cached_endpoint
  meta --> _enums
  _base_endpoint --> _enums
  _base_endpoint --> models
  _cached_endpoint --> _base_endpoint
  _cached_endpoint --> _enums
  _cached_endpoint --> models
  cache --> _base_cache
  cache --> _json_cache
  cache --> _sqlite_cache
  _base_cache --> _enums
  _base_cache --> models
  _json_cache --> _utility
  _json_cache --> _version
  _json_cache --> meta
  _json_cache --> _base_cache
  _json_cache --> models
  _sqlite_cache --> _utility
  _sqlite_cache --> _base_cache
  _sqlite_cache --> models
  _sqlite_cache --> _schema
  models --> _models
  models --> _schema
  _models --> _exceptions
  _models --> _utility
  _schema --> _utility
  _schema --> _decorators
  _schema --> _models
  reports --> _utility
  reports --> meta
  reports --> models
  workspace --> _exceptions
  workspace --> _utility
  workspace --> meta
  workspace --> cache
  workspace --> models
  _project ..> meta
  _tag ..> meta
  _tracker ..> toggl_api
  _tracker ..> cache
  _cached_endpoint ..> _base_cache
  _base_cache ..> meta
  _sqlite_cache ..> meta
