classDiagram
  class toggl_api {
  }
  class _exceptions {
  }
  class client {
  }
  class config {
  }
  class meta {
  }
  class base_endpoint {
  }
  class body {
  }
  class cache {
  }
  class base_cache {
  }
  class json_cache {
  }
  class sqlite_cache {
  }
  class cached_endpoint {
  }
  class enums {
  }
  class models {
  }
  class _decorators {
  }
  class models {
  }
  class schema {
  }
  class organization {
  }
  class project {
  }
  class reports {
  }
  class reports {
  }
  class tag {
  }
  class tracker {
  }
  class user {
  }
  class utility {
  }
  class version {
  }
  class workspace {
  }
  toggl_api --> _exceptions
  toggl_api --> client
  toggl_api --> config
  toggl_api --> meta
  toggl_api --> cache
  toggl_api --> base_cache
  toggl_api --> models
  toggl_api --> organization
  toggl_api --> project
  toggl_api --> tag
  toggl_api --> tracker
  toggl_api --> user
  toggl_api --> version
  toggl_api --> workspace
  client --> _exceptions
  client --> meta
  client --> base_cache
  client --> models
  meta --> base_endpoint
  meta --> body
  meta --> cache
  meta --> cached_endpoint
  meta --> enums
  base_endpoint --> enums
  base_endpoint --> models
  cache --> base_cache
  cache --> json_cache
  base_cache --> enums
  base_cache --> models
  json_cache --> base_cache
  json_cache --> models
  json_cache --> utility
  json_cache --> version
  sqlite_cache --> base_cache
  sqlite_cache --> models
  sqlite_cache --> schema
  sqlite_cache --> utility
  cached_endpoint --> base_endpoint
  cached_endpoint --> enums
  cached_endpoint --> models
  models --> models
  models --> _exceptions
  models --> utility
  schema --> _decorators
  schema --> models
  schema --> utility
  organization --> meta
  organization --> meta
  organization --> models
  project --> _exceptions
  project --> meta
  project --> cache
  project --> models
  project --> utility
  reports --> reports
  reports --> meta
  reports --> enums
  reports --> models
  reports --> utility
  tag --> _exceptions
  tag --> meta
  tag --> base_cache
  tag --> models
  tracker --> _exceptions
  tracker --> meta
  tracker --> models
  tracker --> utility
  user --> toggl_api
  user --> _exceptions
  user --> meta
  user --> models
  user --> utility
  workspace --> _exceptions
  workspace --> meta
  workspace --> body
  workspace --> base_cache
  workspace --> enums
  workspace --> models
  workspace --> utility
  base_cache ..> meta
  json_cache ..> meta
  json_cache ..> cached_endpoint
  sqlite_cache ..> meta
  cached_endpoint ..> cache
  cached_endpoint ..> base_cache
  organization ..> base_cache
  project ..> meta
  tag ..> meta
  tracker ..> toggl_api
  user ..> models
