classDiagram
  class toggl_api {
  }
  class _client {
  }
  class _exceptions {
  }
  class _organization {
  }
  class _project {
  }
  class _tag {
  }
  class _tracker {
  }
  class _user {
  }
  class _utility {
  }
  class _version {
  }
  class _workspace {
  }
  class asyncio {
  }
  class _async_cache {
  }
  class _async_client {
  }
  class _async_endpoint {
  }
  class _async_organization {
  }
  class _async_project {
  }
  class _async_reports {
  }
  class _async_sqlite_cache {
  }
  class _async_tag {
  }
  class _async_tracker {
  }
  class _async_user {
  }
  class _async_workspace {
  }
  class config {
  }
  class meta {
  }
  class _base_endpoint {
  }
  class _body {
  }
  class _cached_endpoint {
  }
  class _enums {
  }
  class cache {
  }
  class _base_cache {
  }
  class _json_cache {
  }
  class _sqlite_cache {
  }
  class models {
  }
  class _decorators {
  }
  class _models {
  }
  class _schema {
  }
  class reports {
  }
  toggl_api --> _client
  toggl_api --> _exceptions
  toggl_api --> _organization
  toggl_api --> _project
  toggl_api --> _tag
  toggl_api --> _tracker
  toggl_api --> _user
  toggl_api --> _version
  toggl_api --> _workspace
  toggl_api --> models
  _client --> _exceptions
  _client --> meta
  _client --> cache
  _client --> models
  _organization --> meta
  _organization --> meta
  _organization --> models
  _project --> _exceptions
  _project --> _utility
  _project --> meta
  _project --> cache
  _project --> models
  _tag --> _exceptions
  _tag --> meta
  _tag --> cache
  _tag --> models
  _tracker --> _exceptions
  _tracker --> _utility
  _tracker --> meta
  _tracker --> cache
  _tracker --> models
  _user --> meta
  _workspace --> _exceptions
  _workspace --> _utility
  _workspace --> meta
  _workspace --> cache
  _workspace --> models
  asyncio --> _async_cache
  asyncio --> _async_client
  asyncio --> _async_endpoint
  asyncio --> _async_organization
  asyncio --> _async_project
  asyncio --> _async_reports
  asyncio --> _async_sqlite_cache
  asyncio --> _async_tag
  asyncio --> _async_tracker
  asyncio --> _async_user
  asyncio --> _async_workspace
  _async_cache --> _exceptions
  _async_cache --> _enums
  _async_cache --> models
  _async_client --> toggl_api
  _async_client --> _async_endpoint
  _async_client --> meta
  _async_endpoint --> _exceptions
  _async_endpoint --> meta
  _async_endpoint --> models
  _async_organization --> _async_endpoint
  _async_organization --> meta
  _async_organization --> models
  _async_project --> toggl_api
  _async_project --> _exceptions
  _async_project --> _async_endpoint
  _async_project --> meta
  _async_reports --> toggl_api
  _async_reports --> _utility
  _async_reports --> _async_endpoint
  _async_reports --> meta
  _async_reports --> reports
  _async_sqlite_cache --> _async_cache
  _async_sqlite_cache --> models
  _async_sqlite_cache --> _schema
  _async_tag --> toggl_api
  _async_tag --> _exceptions
  _async_tag --> _async_endpoint
  _async_tag --> meta
  _async_tracker --> toggl_api
  _async_tracker --> _exceptions
  _async_tracker --> _tracker
  _async_tracker --> _utility
  _async_tracker --> _async_endpoint
  _async_tracker --> meta
  _async_user --> _async_endpoint
  _async_workspace --> toggl_api
  _async_workspace --> _utility
  _async_workspace --> _async_endpoint
  _async_workspace --> meta
  meta --> _base_endpoint
  meta --> _body
  meta --> _cached_endpoint
  meta --> _enums
  _base_endpoint --> _enums
  _base_endpoint --> models
  _cached_endpoint --> _exceptions
  _cached_endpoint --> _base_endpoint
  _cached_endpoint --> _enums
  _cached_endpoint --> models
  cache --> _base_cache
  cache --> _json_cache
  cache --> _sqlite_cache
  _base_cache --> _exceptions
  _base_cache --> _enums
  _base_cache --> models
  _json_cache --> _utility
  _json_cache --> _version
  _json_cache --> _base_cache
  _json_cache --> models
  _sqlite_cache --> _utility
  _sqlite_cache --> _base_cache
  _sqlite_cache --> models
  _sqlite_cache --> _schema
  models --> _models
  models --> _schema
  _models --> _exceptions
  _models --> _utility
  _schema --> _utility
  _schema --> _decorators
  _schema --> _models
  reports --> _exceptions
  reports --> _utility
  reports --> meta
  reports --> models
  _client ..> cache
  _organization ..> cache
  _tracker ..> toggl_api
  _tracker ..> cache
  _workspace ..> toggl_api
  _async_cache ..> _async_endpoint
  _async_client ..> _async_sqlite_cache
  _async_endpoint ..> _async_sqlite_cache
  _async_organization ..> _async_sqlite_cache
  _async_project ..> _project
  _async_project ..> _async_sqlite_cache
  _async_sqlite_cache ..> _async_endpoint
  _async_tag ..> _async_sqlite_cache
  _async_tracker ..> _async_sqlite_cache
  _async_workspace ..> _async_sqlite_cache
  _cached_endpoint ..> _base_cache
  _base_cache ..> meta
  _json_cache ..> meta
  _sqlite_cache ..> meta
