classDiagram
  class toggl_api {
  }
  class client {
  }
  class config {
  }
  class meta {
  }
  class base_endpoint {
  }
  class body {
  }
  class cache {
  }
  class base_cache {
  }
  class json_cache {
  }
  class sqlite_cache {
  }
  class cached_endpoint {
  }
  class enums {
  }
  class models {
  }
  class models {
  }
  class schema {
  }
  class project {
  }
  class reports {
  }
  class reports {
  }
  class tag {
  }
  class tracker {
  }
  class user {
  }
  class utility {
  }
  class version {
  }
  class workspace {
  }
  toggl_api --> client
  toggl_api --> config
  toggl_api --> meta
  toggl_api --> models
  toggl_api --> project
  toggl_api --> tag
  toggl_api --> tracker
  toggl_api --> user
  toggl_api --> version
  toggl_api --> workspace
  client --> meta
  client --> models
  meta --> base_endpoint
  meta --> body
  meta --> cache
  meta --> cached_endpoint
  meta --> enums
  base_endpoint --> enums
  base_endpoint --> models
  cache --> base_cache
  cache --> json_cache
  cache --> sqlite_cache
  base_cache --> enums
  json_cache --> base_cache
  json_cache --> models
  json_cache --> utility
  json_cache --> version
  sqlite_cache --> base_cache
  sqlite_cache --> models
  sqlite_cache --> schema
  sqlite_cache --> utility
  cached_endpoint --> base_endpoint
  cached_endpoint --> enums
  models --> models
  models --> schema
  models --> utility
  schema --> models
  schema --> utility
  project --> meta
  project --> models
  project --> utility
  reports --> reports
  reports --> meta
  reports --> enums
  reports --> models
  reports --> utility
  tag --> meta
  tag --> models
  tracker --> meta
  tracker --> models
  tracker --> utility
  user --> meta
  user --> models
  workspace --> meta
  workspace --> models
  base_cache ..> meta
  base_cache ..> models
  json_cache ..> meta
  json_cache ..> cached_endpoint
  sqlite_cache ..> meta
  cached_endpoint ..> cache
