name: "Deploy Documentation"

env:
  PYTHON_VERSION: "3.10"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: uv sync --group=docs --all-extras

      - name: Deploy website
        run: uv run mkdocs gh-deploy --strict --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
