name: Documentation

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --group docs
      - name: Build site
        run: mkdocs build --strict
