name: Changelog

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  - name: Check out repository
    uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: Generate a changelog
    uses: orhun/git-cliff-action@v3
    with:
      config: cliff.toml
      args: --verbose
    env:
      OUTPUT: docs/CHANGELOG.md
      GITHUB_REPO: ${{ github.repository }}
